/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as IntegrationsBetterAuthRouteImport } from './routes/integrations/better-auth'
import { Route as IntegrationsDrizzleRouteImport } from './routes/integrations/drizzle'
import { Route as IntegrationsPosthogRouteImport } from './routes/integrations/posthog'
import { Route as IntegrationsStripeRouteImport } from './routes/integrations/stripe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as IntegrationsSentryTestingRouteImport } from './routes/integrations/sentry.testing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsBetterAuthRoute = IntegrationsBetterAuthRouteImport.update({
  id: '/integrations/better-auth',
  path: '/integrations/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsDrizzleRoute = IntegrationsDrizzleRouteImport.update({
  id: '/integrations/drizzle',
  path: '/integrations/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsPosthogRoute = IntegrationsPosthogRouteImport.update({
  id: '/integrations/posthog',
  path: '/integrations/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsStripeRoute = IntegrationsStripeRouteImport.update({
  id: '/integrations/stripe',
  path: '/integrations/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSentryTestingRoute =
  IntegrationsSentryTestingRouteImport.update({
    id: '/integrations/sentry/testing',
    path: '/integrations/sentry/testing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/integrations/better-auth': typeof IntegrationsBetterAuthRoute
  '/integrations/drizzle': typeof IntegrationsDrizzleRoute
  '/integrations/posthog': typeof IntegrationsPosthogRoute
  '/integrations/stripe': typeof IntegrationsStripeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations/sentry/testing': typeof IntegrationsSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/integrations/better-auth': typeof IntegrationsBetterAuthRoute
  '/integrations/drizzle': typeof IntegrationsDrizzleRoute
  '/integrations/posthog': typeof IntegrationsPosthogRoute
  '/integrations/stripe': typeof IntegrationsStripeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations/sentry/testing': typeof IntegrationsSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/integrations/better-auth': typeof IntegrationsBetterAuthRoute
  '/integrations/drizzle': typeof IntegrationsDrizzleRoute
  '/integrations/posthog': typeof IntegrationsPosthogRoute
  '/integrations/stripe': typeof IntegrationsStripeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/integrations/sentry/testing': typeof IntegrationsSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/checkout'
    | '/api/stripe-webhook'
    | '/integrations/better-auth'
    | '/integrations/drizzle'
    | '/integrations/posthog'
    | '/integrations/stripe'
    | '/api/auth/$'
    | '/integrations/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/checkout'
    | '/api/stripe-webhook'
    | '/integrations/better-auth'
    | '/integrations/drizzle'
    | '/integrations/posthog'
    | '/integrations/stripe'
    | '/api/auth/$'
    | '/integrations/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/checkout'
    | '/api/stripe-webhook'
    | '/integrations/better-auth'
    | '/integrations/drizzle'
    | '/integrations/posthog'
    | '/integrations/stripe'
    | '/api/auth/$'
    | '/integrations/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  IntegrationsBetterAuthRoute: typeof IntegrationsBetterAuthRoute
  IntegrationsDrizzleRoute: typeof IntegrationsDrizzleRoute
  IntegrationsPosthogRoute: typeof IntegrationsPosthogRoute
  IntegrationsStripeRoute: typeof IntegrationsStripeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  IntegrationsSentryTestingRoute: typeof IntegrationsSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/better-auth': {
      id: '/integrations/better-auth'
      path: '/integrations/better-auth'
      fullPath: '/integrations/better-auth'
      preLoaderRoute: typeof IntegrationsBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/drizzle': {
      id: '/integrations/drizzle'
      path: '/integrations/drizzle'
      fullPath: '/integrations/drizzle'
      preLoaderRoute: typeof IntegrationsDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/posthog': {
      id: '/integrations/posthog'
      path: '/integrations/posthog'
      fullPath: '/integrations/posthog'
      preLoaderRoute: typeof IntegrationsPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/stripe': {
      id: '/integrations/stripe'
      path: '/integrations/stripe'
      fullPath: '/integrations/stripe'
      preLoaderRoute: typeof IntegrationsStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/sentry/testing': {
      id: '/integrations/sentry/testing'
      path: '/integrations/sentry/testing'
      fullPath: '/integrations/sentry/testing'
      preLoaderRoute: typeof IntegrationsSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  IntegrationsBetterAuthRoute: IntegrationsBetterAuthRoute,
  IntegrationsDrizzleRoute: IntegrationsDrizzleRoute,
  IntegrationsPosthogRoute: IntegrationsPosthogRoute,
  IntegrationsStripeRoute: IntegrationsStripeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  IntegrationsSentryTestingRoute: IntegrationsSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
